export const PROFESSIONS = [
  { value: 'lawyer', label: 'Lawyer', category: 'professional' },
  { value: 'consultant', label: 'Business Consultant', category: 'professional' },
  { value: 'accountant', label: 'Accountant', category: 'professional' },
  { value: 'financial-advisor', label: 'Financial Advisor', category: 'professional' },
  { value: 'real-estate-agent', label: 'Real Estate Agent', category: 'professional' },
  { value: 'doctor', label: 'Doctor', category: 'healthcare' },
  { value: 'dentist', label: 'Dentist', category: 'healthcare' },
  { value: 'therapist', label: 'Therapist', category: 'healthcare' },
  { value: 'psychologist', label: 'Psychologist', category: 'healthcare' },
  { value: 'nutritionist', label: 'Nutritionist', category: 'healthcare' },
  { value: 'chiropractor', label: 'Chiropractor', category: 'healthcare' },
  { value: 'designer', label: 'Graphic Designer', category: 'creative' },
  { value: 'photographer', label: 'Photographer', category: 'creative' },
  { value: 'artist', label: 'Artist', category: 'creative' },
  { value: 'videographer', label: 'Videographer', category: 'creative' },
  { value: 'web-developer', label: 'Web Developer', category: 'creative' },
  { value: 'content-creator', label: 'Content Creator', category: 'creative' },
  { value: 'interior-designer', label: 'Interior Designer', category: 'creative' },
];
